CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- TODO: Create comments table (id INT AUTO_INCREMENT PRIMARY KEY, post_id INT NOT NULL FK, body TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)
